"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 15:46:47.489891
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=60), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('src_type', sa.String(length=20), nullable=False),
    sa.Column('src_id', sa.String(length=80), nullable=False),
    sa.Column('rel', sa.String(length=30), nullable=False),
    sa.Column('dst_type', sa.String(length=20), nullable=False),
    sa.Column('dst_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'src_type', 'src_id', 'rel', 'dst_type', 'dst_id')
    )
    op.create_index(op.f('ix_graph_edges_dst_id'), 'graph_edges', ['dst_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_src_id'), 'graph_edges', ['src_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_workspace_id'), 'graph_edges', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('policy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_memory',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=True),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('peak_score', sa.Integer(), nullable=False),
    sa.Column('peak_tier', sa.String(length=10), nullable=False),
    sa.Column('evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('bank_hmacs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_memory_vendor_id'), 'case_memory', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_case_memory_workspace_id'), 'case_memory', ['workspace_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'sha256')
    )
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.String(length=40), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_workspace_id'), 'invitations', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_workspace_id'), 'vendors', ['workspace_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extraction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('corrections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recommendation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('memory_hits', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('partial', sa.Boolean(), nullable=False),
    sa.Column('budget', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sources_checked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_vendor_id'), 'cases', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_cases_workspace_id'), 'cases', ['workspace_id'], unique=False)
    op.create_table('historical_invoices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('invoice_number_norm', sa.String(length=80), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank_last4', sa.String(length=4), nullable=True),
    sa.Column('bank_hmac', sa.String(length=64), nullable=True),
    sa.Column('po_number', sa.String(length=80), nullable=True),
    sa.Column('line_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_invoices_invoice_number_norm'), 'historical_invoices', ['invoice_number_norm'], unique=False)
    op.create_index(op.f('ix_historical_invoices_vendor_id'), 'historical_invoices', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_historical_invoices_workspace_id'), 'historical_invoices', ['workspace_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('po_number', sa.String(length=80), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('lines', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_workspace_id'), 'purchase_orders', ['workspace_id'], unique=False)
    op.create_table('vendor_bank_accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('acct_hmac', sa.String(length=64), nullable=False),
    sa.Column('acct_enc', sa.LargeBinary(), nullable=True),
    sa.Column('ifsc', sa.String(length=11), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_method', sa.String(length=40), nullable=True),
    sa.Column('verified_by', sa.String(length=40), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_bank_accounts_acct_hmac'), 'vendor_bank_accounts', ['acct_hmac'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_vendor_id'), 'vendor_bank_accounts', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_bank_accounts_workspace_id'), 'vendor_bank_accounts', ['workspace_id'], unique=False)
    op.create_table('vendor_contacts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_contacts_vendor_id'), 'vendor_contacts', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_contacts_workspace_id'), 'vendor_contacts', ['workspace_id'], unique=False)
    op.create_table('vendor_domains',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.String(length=40), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_method', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_domains_vendor_id'), 'vendor_domains', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_domains_workspace_id'), 'vendor_domains', ['workspace_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('signal', sa.String(length=60), nullable=True),
    sa.Column('assertion', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('verifier_notes', sa.Text(), nullable=True),
    sa.Column('supporting_quote', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_workspace_id'), 'claims', ['workspace_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_case_id'), 'decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_decisions_workspace_id'), 'decisions', ['workspace_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('to_email', sa.String(length=200), nullable=False),
    sa.Column('recipient_verified', sa.Boolean(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('requested_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=40), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_case_id'), 'drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_drafts_workspace_id'), 'drafts', ['workspace_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=True),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_workspace_id'), 'evidence', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('from_email', sa.String(length=200), nullable=False),
    sa.Column('to_email', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('weights_version', sa.String(length=10), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contributions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_case_id'), 'risk_scores', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_workspace_id'), 'risk_scores', ['workspace_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_case_id'), 'agent_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_events_workspace_id'), 'agent_events', ['workspace_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=True),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_case_id'), 'llm_calls', ['case_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_workspace_id'), 'llm_calls', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_calls_workspace_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_case_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_agent_events_workspace_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_case_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_risk_scores_workspace_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_case_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evidence_workspace_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_drafts_workspace_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_case_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_decisions_workspace_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_case_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_claims_workspace_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_vendor_domains_workspace_id'), table_name='vendor_domains')
    op.drop_index(op.f('ix_vendor_domains_vendor_id'), table_name='vendor_domains')
    op.drop_table('vendor_domains')
    op.drop_index(op.f('ix_vendor_contacts_workspace_id'), table_name='vendor_contacts')
    op.drop_index(op.f('ix_vendor_contacts_vendor_id'), table_name='vendor_contacts')
    op.drop_table('vendor_contacts')
    op.drop_index(op.f('ix_vendor_bank_accounts_workspace_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_vendor_id'), table_name='vendor_bank_accounts')
    op.drop_index(op.f('ix_vendor_bank_accounts_acct_hmac'), table_name='vendor_bank_accounts')
    op.drop_table('vendor_bank_accounts')
    op.drop_index(op.f('ix_purchase_orders_workspace_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_historical_invoices_workspace_id'), table_name='historical_invoices')
    op.drop_index(op.f('ix_historical_invoices_vendor_id'), table_name='historical_invoices')
    op.drop_index(op.f('ix_historical_invoices_invoice_number_norm'), table_name='historical_invoices')
    op.drop_table('historical_invoices')
    op.drop_index(op.f('ix_cases_workspace_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_vendor_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_vendors_workspace_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invitations_workspace_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_case_memory_workspace_id'), table_name='case_memory')
    op.drop_index(op.f('ix_case_memory_vendor_id'), table_name='case_memory')
    op.drop_table('case_memory')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_graph_edges_workspace_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_src_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_dst_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
