"""vendor archive notes imports

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 16:34:51.210718
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_ok', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imports_workspace_id'), 'imports', ['workspace_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('author_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_notes_workspace_id'), 'case_notes', ['workspace_id'], unique=False)
    op.add_column('vendors', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('vendors', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    for t in ("imports", "case_notes"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY tenant_isolation ON {t} USING (workspace_id = current_setting('app.workspace_id', true)) "
                   f"WITH CHECK (workspace_id = current_setting('app.workspace_id', true))")
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'probity_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON imports, case_notes TO probity_app;
                GRANT SELECT ON alembic_version TO probity_app;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'notes')
    op.drop_column('vendors', 'archived')
    op.drop_index(op.f('ix_case_notes_workspace_id'), table_name='case_notes')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_imports_workspace_id'), table_name='imports')
    op.drop_table('imports')
    # ### end Alembic commands ###
