"""verification provenance

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-04 17:45:28.390330
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_bank_accounts', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vendor_bank_accounts', sa.Column('verified_note', sa.Text(), nullable=True))
    op.add_column('vendor_contacts', sa.Column('verified_method', sa.String(length=40), nullable=True))
    op.add_column('vendor_contacts', sa.Column('verified_by', sa.String(length=40), nullable=True))
    op.add_column('vendor_contacts', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vendor_contacts', sa.Column('verified_note', sa.Text(), nullable=True))
    op.add_column('vendor_domains', sa.Column('verified_by', sa.String(length=40), nullable=True))
    op.add_column('vendor_domains', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vendor_domains', sa.Column('verified_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_domains', 'verified_note')
    op.drop_column('vendor_domains', 'verified_at')
    op.drop_column('vendor_domains', 'verified_by')
    op.drop_column('vendor_contacts', 'verified_note')
    op.drop_column('vendor_contacts', 'verified_at')
    op.drop_column('vendor_contacts', 'verified_by')
    op.drop_column('vendor_contacts', 'verified_method')
    op.drop_column('vendor_bank_accounts', 'verified_note')
    op.drop_column('vendor_bank_accounts', 'verified_at')
    # ### end Alembic commands ###
